// AboutScreen.jsx
// About ComfortMap — mission, what it does, and credits.

import { useNavigate } from 'react-router-dom'
import { useUser } from '../context/UserContext'
import { RADIUS } from '../styles/colors'
import Header from '../components/Header'
import Screen from '../components/Screen'
import pkg from '../../package.json'

function Section({ title, children, COLORS }) {
  return (
    <div style={{ marginBottom: 22 }}>
      <div style={{ fontSize: 13, fontWeight: 700, color: COLORS.mint, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
        {title}
      </div>
      <div style={{ fontSize: 14, color: COLORS.text, lineHeight: 1.65 }}>
        {children}
      </div>
    </div>
  )
}

export default function AboutScreen() {
  const navigate = useNavigate()
  const { COLORS } = useUser()

  const FACTS = [
    ['🌍', '10 languages'],
    ['🏙️', '16 venue types'],
    ['🧠', '8 sensory profiles'],
    ['🆓', 'Free to use'],
  ]

  return (
    <div style={{ minHeight: '100vh', background: COLORS.soft }}>
      <Header title="About ComfortMap" onBack={() => navigate(-1)} />
      <Screen>
        <div style={{ textAlign: 'center', margin: '28px 0 24px' }}>
          <div style={{ fontSize: 56, marginBottom: 12 }}>🗺️</div>
          <div style={{ fontSize: 24, fontWeight: 800, color: COLORS.forest, letterSpacing: -0.5 }}>
            ComfortMap
          </div>
          <div style={{ fontSize: 13, color: COLORS.muted, marginTop: 4 }}>
            Version {pkg.version}
          </div>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: 10,
          marginBottom: 24,
        }}>
          {FACTS.map(([emoji, label]) => (
            <div key={label} style={{
              background: COLORS.white,
              border: `1.5px solid ${COLORS.border}`,
              borderRadius: RADIUS.md,
              padding: '12px 10px',
              textAlign: 'center',
            }}>
              <div style={{ fontSize: 20, marginBottom: 4 }}>{emoji}</div>
              <div style={{ fontSize: 12, color: COLORS.muted, fontWeight: 600 }}>{label}</div>
            </div>
          ))}
        </div>

        <Section title="Our mission" COLORS={COLORS}>
          Walking into an unfamiliar place is one of the most common sources of everyday anxiety —
          for autistic people, people with sensory sensitivities, anxiety disorders, chronic illness,
          or anyone facing somewhere new for the first time. ComfortMap exists to remove the fear of
          the unknown by telling you, in plain language, exactly what to expect before you go: the
          noise, the crowds, the lighting, how to get in, what people will say, and how to leave if
          you need to.
        </Section>

        <Section title="What it does" COLORS={COLORS}>
          Tell ComfortMap where you're going — a restaurant, an airport, a first day at a new school,
          anywhere — and it builds a short, calm "comfort map" covering noise levels, crowd patterns,
          sensory triggers, step-by-step what-to-expect, and practical tips, tailored to your sensory
          profile and who the visit is for.
        </Section>

        <Section title="Built with Claude" COLORS={COLORS}>
          Every comfort map is generated by Claude, Anthropic's AI model, based on the details you
          share and your sensory profile. Claude never remembers you between visits — every map is
          generated fresh from what you tell it.
        </Section>

        <Section title="Get in touch" COLORS={COLORS}>
          Questions, feedback, or ideas? We'd love to hear from you at{' '}
          <span style={{ color: COLORS.green, fontWeight: 600 }}>hello@comfortmap.app</span>.
        </Section>

        <div style={{ textAlign: 'center', fontSize: 12, color: COLORS.muted, marginTop: 32, marginBottom: 12 }}>
          Made with care for anyone who's ever felt anxious about somewhere new. 💚
        </div>
      </Screen>
    </div>
  )
}
