// TermsScreen.jsx
// Terms of Service — plain-language terms matching the actual behavior
// of the app (rate limits from utils/rateLimit.js, AI content from
// api/comfort.js).

import { useNavigate } from 'react-router-dom'
import { useUser } from '../context/UserContext'
import { getText } from '../data/languages'
import { RADIUS } from '../styles/colors'
import Header from '../components/Header'
import Screen from '../components/Screen'

function Section({ title, children, COLORS }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{ fontSize: 15, fontWeight: 700, color: COLORS.forest, marginBottom: 6 }}>
        {title}
      </div>
      <div style={{ fontSize: 14, color: COLORS.text, lineHeight: 1.65 }}>
        {children}
      </div>
    </div>
  )
}

export default function TermsScreen() {
  const navigate = useNavigate()
  const { COLORS, lang } = useUser()
  const t = getText(lang)

  return (
    <div style={{ minHeight: '100vh', background: COLORS.pale }}>
      <Header title={t.terms || 'Terms of Service'} onBack={() => navigate(-1)} />
      <Screen>
        <p style={{ fontSize: 13, color: COLORS.muted, margin: '16px 0 20px', lineHeight: 1.6 }}>
          Last updated July 2026. These are the terms for using ComfortMap — written in plain
          language, no legalese. By using ComfortMap, you agree to them.
        </p>

        <div style={{
          background: COLORS.warn,
          border: `1px solid ${COLORS.warnBorder}`,
          borderRadius: RADIUS.md,
          padding: '12px 14px',
          marginBottom: 22,
          fontSize: 13,
          color: COLORS.warnText,
          lineHeight: 1.6,
        }}>
          ⚕️ ComfortMap is not a medical, therapeutic, or diagnostic service. It does not replace
          advice from a doctor, therapist, or other qualified professional.
        </div>

        <Section title="1. What ComfortMap is" COLORS={COLORS}>
          ComfortMap helps you feel more prepared before visiting an unfamiliar place by giving
          you a general sense of what to expect — noise, crowds, lighting, and similar sensory
          factors. It's a comfort and preparation tool, not a guarantee of what you'll actually
          encounter. Conditions at any real place can change at any time.
        </Section>

        <Section title="2. Free to use, with a monthly limit" COLORS={COLORS}>
          ComfortMap is free to use. To keep the service available and sustainable for everyone,
          each person can create a limited number of new comfort maps per month, which resets at
          the start of each month. Asking follow-up questions about a map you've already generated
          doesn't count against this limit. We may adjust this limit over time as the service
          grows. If you'd like a higher monthly limit, an optional paid subscription
          (ComfortMap Pro) is available for a recurring monthly fee. Pro is entirely optional —
          ComfortMap remains free to use. You can cancel your subscription at any time; see our
          Refund Policy for details.
        </Section>

        <Section title="3. Subscriptions & billing (ComfortMap Pro)" COLORS={COLORS}>
          ComfortMap Pro is an optional paid subscription. It is billed monthly in advance through
          our payment processor, Stripe, and renews automatically each month until you cancel — by
          subscribing, you authorize this recurring charge to your chosen payment method. You can
          cancel at any time; your Pro access continues through the end of the billing period
          you've already paid for, after which your account returns to the free tier. Refunds are
          handled as described in our Refund Policy. Prices may change in the future; if they do,
          we'll give notice, and any change applies only to future billing periods — never ones
          you've already paid. You are responsible for any taxes that apply.
        </Section>

        <Section title="4. No medical advice" COLORS={COLORS}>
          ComfortMap is not a substitute for professional medical, psychological, or therapeutic
          advice, diagnosis, or treatment. Nothing in a comfort map should be treated as clinical
          guidance for anxiety, sensory processing differences, or any other condition. Always
          seek the advice of a qualified health provider with any questions you have about a
          medical or mental health condition, and never disregard professional advice or delay
          seeking it because of something you read here.
        </Section>

        <Section title="5. AI-generated content" COLORS={COLORS}>
          Comfort maps are generated by an AI model (Claude, by Anthropic) based on the
          information you provide. AI-generated content can be incorrect, outdated, or not
          reflect the specific place you're actually visiting — it's a best-effort estimate, not
          verified fact. Use your own judgment, and treat every comfort map as a starting point
          for preparation rather than a confirmed description of a real location.
        </Section>

        <Section title="6. Acceptable use" COLORS={COLORS}>
          Please use ComfortMap only for its intended purpose: preparing yourself or someone you
          support for a real visit to a real place. In particular, don't:
          <ul style={{ margin: '8px 0 0', paddingLeft: 20, lineHeight: 1.7 }}>
            <li>Use ComfortMap to generate harmful, harassing, hateful, or illegal content</li>
            <li>Attempt to bypass, automate, or abuse the monthly usage limit</li>
            <li>Send malicious input intended to attack, exploit, or disrupt the service</li>
            <li>Use ComfortMap's output as a substitute for professional or emergency advice</li>
            <li>Scrape, resell, or use the service to build a competing product</li>
          </ul>
          We reserve the right to block access for anyone who misuses the service.
        </Section>

        <Section title="7. No warranty" COLORS={COLORS}>
          ComfortMap is provided "as is," without warranties of any kind. We don't guarantee the
          service will be uninterrupted, error-free, or that any comfort map will be accurate for
          your specific visit.
        </Section>

        <Section title="8. Limitation of liability" COLORS={COLORS}>
          To the fullest extent permitted by law, ComfortMap and its creators aren't liable for
          any harm, loss, or negative outcome arising from your use of the app or reliance on
          AI-generated content, including decisions made about a visit based on a comfort map.
        </Section>

        <Section title="9. Changes to these terms" COLORS={COLORS}>
          If these terms change, this page will be updated and the "last updated" date above will
          reflect it. Continuing to use ComfortMap after a change means you accept the updated
          terms.
        </Section>

        <Section title="Questions" COLORS={COLORS}>
          Reach out any time at{' '}
          <span style={{ color: COLORS.green, fontWeight: 600 }}>hello@comfortmap.app</span>.
        </Section>
      </Screen>
    </div>
  )
}
